import cover from '../../public/assets/images/aiftpcover.jpg';

const journalContent = [
    {
        id:1,
        img:cover,
        month:'January',
        year:'2025',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:2,
        img:cover,
        month:'February',
        year:'2025',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:3,
        img:cover,
        month:'March',
        year:'2025',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:4,
        img:cover,
        month:'April',
        year:'2025',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:5,
        img:cover,
        month:'January',
        year:'2024',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:6,
        img:cover,
        month:'February',
        year:'2024',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:7,
        img:cover,
        month:'January',
        year:'2023',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:8,
        img:cover,
        month:'February',
        year:'2023',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:9,
        img:cover,
        month:'January',
        year:'2022',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:10,
        img:cover,
        month:'February',
        year:'2022',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:11,
        img:cover,
        month:'January',
        year:'2021',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:12,
        img:cover,
        month:'February',
        year:'2021',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:13,
        img:cover,
        month:'January',
        year:'2020',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
    {
        id:14,
        img:cover,
        month:'February',
        year:'2020',
        link:'https://aiftponline.org/wp-content/uploads/2024/05/aiftp-dec-cover-2023.pdf'
    },
   ]

   export default journalContent;